// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-KGnA0hYxcXFndODtBB0Zn2W93AU2qg',
    appId: '1:403168953726:web:fd3cab08e12c27e80b1f2f',
    messagingSenderId: '403168953726',
    projectId: 'squashdisease',
    authDomain: 'squashdisease.firebaseapp.com',
    storageBucket: 'squashdisease.firebasestorage.app',
    measurementId: 'G-8YFJ9ZYJMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXbFee-KwD93UgPofvaYa5isjwDiqcXo0',
    appId: '1:403168953726:android:91432d82debc266c0b1f2f',
    messagingSenderId: '403168953726',
    projectId: 'squashdisease',
    storageBucket: 'squashdisease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARVbb0e5w0LuTe0MEg03h_kD1WU4s5hBo',
    appId: '1:403168953726:ios:4aedfae6ca0ad9610b1f2f',
    messagingSenderId: '403168953726',
    projectId: 'squashdisease',
    storageBucket: 'squashdisease.firebasestorage.app',
    iosBundleId: 'com.example.squashDisease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARVbb0e5w0LuTe0MEg03h_kD1WU4s5hBo',
    appId: '1:403168953726:ios:4aedfae6ca0ad9610b1f2f',
    messagingSenderId: '403168953726',
    projectId: 'squashdisease',
    storageBucket: 'squashdisease.firebasestorage.app',
    iosBundleId: 'com.example.squashDisease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-KGnA0hYxcXFndODtBB0Zn2W93AU2qg',
    appId: '1:403168953726:web:0ff762ab07b1be410b1f2f',
    messagingSenderId: '403168953726',
    projectId: 'squashdisease',
    authDomain: 'squashdisease.firebaseapp.com',
    storageBucket: 'squashdisease.firebasestorage.app',
    measurementId: 'G-C1SK1SCC82',
  );
}
